spring:
  profiles:
    active: local #default profile

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE